database:
  dbname: 'word_bot'
  user: 'user'
  password: ''
  host: 'localhost'
  port: '5432'
  db_url: 'postgresql://postgresql:'

test_database:
  dbname: 'test_word_bot'
  user: 'user'
  password: 'password'
  host: 'localhost'
  port: '5432'

redis:
  host: 'localhost'
  port: 6379
  password: ''
  db: 0  # номер базы данных Redis
  ttl: 3600  # время жизни ключей в секундах
  prefix: 'word_bot:'  # префикс для ключей
